App_Blog/urls.py

from django.urls import path

from App_Blog import views

app_name = 'App_Blog'

urlpatterns = [
   # path('', views.search_view, name='search'),
    path('', views.BlogList.as_view(), name='blog_list'),
    path('write/', views.CreateBlog.as_view(), name='create_blog'),
    path('details/<slug>/', views.blog_details, name='blog_details'),
    path('liked/<pk>/', views.liked, name='liked_post'),
    path('unliked/<pk>/', views.unliked, name='unliked_post'),
    path('delete/<pk>/', views.delete, name='delete_post'),
    path('my-blogs/', views.MyBlogs.as_view(), name='my_blogs'),
    path('edit/<pk>/', views.UpdateBlog.as_view(), name='edit_blog'),
]

App_Login/urls.py
from django.urls import path
from App_Login import views

app_name = 'App_Login'

urlpatterns = [
   path('signup/', views.sign_up, name='signup'),
   path('login/', views.login_page, name='login'),
   path('logout/', views.logout_user, name='logout'),
   path('profile/', views.profile, name='profile'),
   path('change-profile/', views.user_change, name='user_change'),
   path('password/', views.pass_change, name='pass_change'),
   path('add-picture/', views.add_pro_pic, name='add_pro_pic'),
   path('change-picture/', views.change_pro_pic, name='change_pro_pic'),
]

My_Blog_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('App_Login.urls')),
    path('blog/', include('App_Blog.urls')),
    path('', views.Index, name='index'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous">
    <title> {% block title_block %} Blogs {% endblock %} </title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'index' %} "><img src="/media/kisspng-blogger.png"  width="50px" alt=""></a>
                
              </li>
              {% if user.is_authenticated %}
              <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                  @{{user.username}}
                </button>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                  <li><a class="dropdown-item"  href="{% url 'App_Blog:create_blog' %} ">Write Blog</a></li>
                  <li><a class="dropdown-item"  href="{% url 'App_Blog:my_blogs' %} ">My Blogs</a></li>
                  <li><a class="dropdown-item"  href="{% url 'App_Login:profile' %} ">Your Profile</a></li>
                  <hr>
                  <li><a class="dropdown-item"  href="{% url 'App_Login:logout' %} ">Logout</a></li>
                </ul>
              </div>
              {% else %}
              <li class="nav-item">
                <a class="nav-link "  href="{% url 'App_Login:signup' %} ">Sign Up</a>
              </li>
              <li class="nav-item">
                <a class="nav-link "  href="{% url 'App_Login:login' %} ">Login</a>
              </li>
              {% endif %}
              <div class="row">
                    <div class="input-group">
                        <input class="form-control border-end-0 border rounded-pill" type="search" value="search" id="example-search-input">
                        <span class="input-group-append">
                            <button class="btn btn-outline-secondary bg-white border-bottom-0 border rounded-pill ms-n5" type="button">
                                <i class="fa fa-search"></i>
                            </button>
                        </span>
                    </div>
                </div>
            </div>
          </div>
        </div>
      </nav>
      
      <div class="container" style="padding: top 20px;">
        {% block body_block %}

        {% endblock %}
      </div>

    
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
</body>
</html>


                
                
                

                